#include "pythontarget.h"
#include <limits.h>
#include "low_level_platform/api/low_level_platform.h"
#include "include/api/schedule.h"
#include "include/core/reactor.h"
#include "include/core/reactor_common.h"
#include "include/core/threaded/scheduler.h"
#include "include/core/mixed_radix.h"
#include "include/core/port.h"
#include "include/core/environment.h"
int lf_reactor_c_main(int argc, const char* argv[]);
// Code generated by the Lingua Franca compiler from:
// file://Users/russl8/github/lf-py/pingpong/src/Pingpong.lf
#define LOG_LEVEL 2

int main(int argc, const char* argv[]) {
    return lf_reactor_c_main(argc, argv);
}
void lf_set_default_command_line_options() {}
#include "_player.h"
#include "__lf_gendelay_0.h"
#include "_pingpong_main.h"
typedef enum {
    pingpong_main,
    num_environments
} _enclave_id;
// The global array of environments associated with each enclave
static environment_t environments[num_environments];
// 'Create' and initialize the environments in the program
void lf_create_environments() {
    environment_init(&environments[pingpong_main],"pingpong_main",pingpong_main,_lf_number_of_workers,0,2,0,0,6,0,0,0,NULL);
}
// Update the pointer argument to point to the beginning of the environment array
// and return the size of that array
int _lf_get_environments(environment_t ** return_envs) {
   (*return_envs) = (environment_t *) environments;
   return num_environments;
}
// Arrays representing the enclaves downstream of `pingpong_main_downstream`
#define PINGPONG_MAIN_NUM_DOWNSTREAM 0
// No downstreams, but 0-length arrays not allowed by MSVC (C2466)
int pingpong_main_downstream[1] = {-1};
// Arrays representing the enclaves upstream of `pingpong_main_upstream`
#define PINGPONG_MAIN_NUM_UPSTREAM 0
// No upstreams, but 0-length arrays not allowed by MSVC (C2466)
int pingpong_main_upstream[1] = {-1};
// No upstreams, but 0-length arrays not allowed by MSVC (C2466)
interval_t pingpong_main_upstream_delay[1] = {FOREVER};
// Writes a pointer to the array of upstream enclaves into `result` and returns the length
int lf_get_upstream_of(int enclave_id, int ** result) {
    int num_upstream;
    int* upstream;
    switch(enclave_id) { 
        case pingpong_main:
            num_upstream = PINGPONG_MAIN_NUM_UPSTREAM;
            upstream = &pingpong_main_upstream[0];
            break;
        default:
            lf_print_error_and_exit("Illegal enclave_id %u", enclave_id);
            break;
        }
    (*result) = upstream;
    return num_upstream;
}
// Writes a pointer to the array of downstream enclaves into `result` and returns the length
int lf_get_downstream_of(int enclave_id, int ** result) {
    int num_downstream;
    int* downstream;
    switch(enclave_id) { 
        case pingpong_main:
            num_downstream = PINGPONG_MAIN_NUM_DOWNSTREAM;
            downstream = &pingpong_main_downstream[0];
            break;
        default:
            lf_print_error_and_exit("Illegal enclave_id %u", enclave_id);
            break;
        }
    (*result) = downstream;
    return num_downstream;
}
// Writes a pointer to the array of upstream delays into `result` and returns the length
int lf_get_upstream_delay_of(int enclave_id, interval_t ** result) {
    int num_upstream;
    interval_t* delay;
    switch(enclave_id) { 
        case pingpong_main:
            num_upstream = PINGPONG_MAIN_NUM_UPSTREAM;
            delay = &pingpong_main_upstream_delay[0];
            break;
        default:
            lf_print_error_and_exit("Illegal enclave_id %u", enclave_id);
            break;
        }
    (*result) = delay;
    return num_upstream;
}
void _lf_initialize_trigger_objects() {
    int startup_reaction_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(startup_reaction_count);
    int shutdown_reaction_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(shutdown_reaction_count);
    int reset_reaction_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(reset_reaction_count);
    int timer_triggers_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(timer_triggers_count);
    int modal_state_reset_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(modal_state_reset_count);
    int modal_reactor_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(modal_reactor_count);
    int watchdog_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(watchdog_count);
    int bank_index;
    SUPPRESS_UNUSED_WARNING(bank_index);
    int watchdog_number = 0;
    SUPPRESS_UNUSED_WARNING(watchdog_number);
    _pingpong_main_main_self_t* pingpong_main_self[1];
    SUPPRESS_UNUSED_WARNING(pingpong_main_self);
    _player_self_t* pingpong_p1_self[1];
    SUPPRESS_UNUSED_WARNING(pingpong_p1_self);
    _player_self_t* pingpong_p2_self[1];
    SUPPRESS_UNUSED_WARNING(pingpong_p2_self);
    __lf_gendelay_0_self_t* pingpong_delay_self[1];
    SUPPRESS_UNUSED_WARNING(pingpong_delay_self);
    // ***** Start initializing Pingpong of class Pingpong
    pingpong_main_self[0] = new__pingpong_main();
    pingpong_main_self[0]->base.environment = &environments[pingpong_main];
    pingpong_main_self[0]->_lf_name = "pingpong_main_lf";
    if (set_python_field_to_c_pointer("__main__",
        pingpong_main_self[0]->_lf_name,
        0,
        "lf_self",
        pingpong_main_self[0])) {
      lf_print_error_and_exit("Could not set lf_self pointer Pingpong");
    }
    
    #if !defined LF_SINGLE_THREADED
    pingpong_main_self[0]->base.reactor_mutex = NULL;
    #endif
    {
        _pingpong_main_main_self_t *self = pingpong_main_self[0];
        // ***** Start initializing Pingpong.p1 of class Player
        pingpong_p1_self[0] = new__player();
        pingpong_p1_self[0]->base.environment = &environments[pingpong_main];
        pingpong_p1_self[0]->_lf_name = "pingpong_p1_lf";
        pingpong_p1_self[0]->_lf_py_reaction_function_0 = 
        get_python_function("__main__", 
            pingpong_p1_self[0]->_lf_name,
            0,
            "reaction_function_0");
        if(pingpong_p1_self[0]->_lf_py_reaction_function_0 == NULL) {
            lf_print_error_and_exit("Could not load function reaction_function_0");
        }
        pingpong_p1_self[0]->_lf_py_reaction_function_1 = 
        get_python_function("__main__", 
            pingpong_p1_self[0]->_lf_name,
            0,
            "reaction_function_1");
        if(pingpong_p1_self[0]->_lf_py_reaction_function_1 == NULL) {
            lf_print_error_and_exit("Could not load function reaction_function_1");
        }
        pingpong_p1_self[0]->_lf_py_reaction_function_2 = 
        get_python_function("__main__", 
            pingpong_p1_self[0]->_lf_name,
            0,
            "reaction_function_2");
        if(pingpong_p1_self[0]->_lf_py_reaction_function_2 == NULL) {
            lf_print_error_and_exit("Could not load function reaction_function_2");
        }
        if (set_python_field_to_c_pointer("__main__",
            pingpong_p1_self[0]->_lf_name,
            0,
            "lf_self",
            pingpong_p1_self[0])) {
          lf_print_error_and_exit("Could not set lf_self pointer p1");
        }
        
        
        // width of -2 indicates that it is not a multiport.
        pingpong_p1_self[0]->_lf_ballOut_width = -2;
        // width of -2 indicates that it is not a multiport.
        pingpong_p1_self[0]->_lf_ballIn_width = -2;
        environments[pingpong_main].startup_reactions[startup_reaction_count[pingpong_main]++] = &pingpong_p1_self[0]->_lf__reaction_0;
        // Initializing action Pingpong.p1.a
        pingpong_p1_self[0]->_lf__a.offset = 0;
        pingpong_p1_self[0]->_lf__a.period = -1;
        pingpong_p1_self[0]->_lf__a.last_tag = NEVER_TAG;
        pingpong_p1_self[0]->_lf__a.mode = NULL;
        _lf_initialize_template((token_template_t*)
                &(pingpong_p1_self[0]->_lf__a),
        0);
        _lf_initialize_template((token_template_t*)
                &(pingpong_p1_self[0]->_lf_a),
        0);
        pingpong_p1_self[0]->_lf__a.status = absent;
        pingpong_p1_self[0]->_lf__reaction_0.deadline = NEVER;
        pingpong_p1_self[0]->_lf__reaction_1.deadline = NEVER;
        pingpong_p1_self[0]->_lf__reaction_2.deadline = NEVER;
        #if !defined LF_SINGLE_THREADED
        pingpong_p1_self[0]->base.reactor_mutex = NULL;
        #endif
        //***** End initializing Pingpong.p1
    }
    {
        _pingpong_main_main_self_t *self = pingpong_main_self[0];
        // ***** Start initializing Pingpong.p2 of class Player
        pingpong_p2_self[0] = new__player();
        pingpong_p2_self[0]->base.environment = &environments[pingpong_main];
        pingpong_p2_self[0]->_lf_name = "pingpong_p2_lf";
        pingpong_p2_self[0]->_lf_py_reaction_function_0 = 
        get_python_function("__main__", 
            pingpong_p2_self[0]->_lf_name,
            0,
            "reaction_function_0");
        if(pingpong_p2_self[0]->_lf_py_reaction_function_0 == NULL) {
            lf_print_error_and_exit("Could not load function reaction_function_0");
        }
        pingpong_p2_self[0]->_lf_py_reaction_function_1 = 
        get_python_function("__main__", 
            pingpong_p2_self[0]->_lf_name,
            0,
            "reaction_function_1");
        if(pingpong_p2_self[0]->_lf_py_reaction_function_1 == NULL) {
            lf_print_error_and_exit("Could not load function reaction_function_1");
        }
        pingpong_p2_self[0]->_lf_py_reaction_function_2 = 
        get_python_function("__main__", 
            pingpong_p2_self[0]->_lf_name,
            0,
            "reaction_function_2");
        if(pingpong_p2_self[0]->_lf_py_reaction_function_2 == NULL) {
            lf_print_error_and_exit("Could not load function reaction_function_2");
        }
        if (set_python_field_to_c_pointer("__main__",
            pingpong_p2_self[0]->_lf_name,
            0,
            "lf_self",
            pingpong_p2_self[0])) {
          lf_print_error_and_exit("Could not set lf_self pointer p2");
        }
        
        
        // width of -2 indicates that it is not a multiport.
        pingpong_p2_self[0]->_lf_ballOut_width = -2;
        // width of -2 indicates that it is not a multiport.
        pingpong_p2_self[0]->_lf_ballIn_width = -2;
        environments[pingpong_main].startup_reactions[startup_reaction_count[pingpong_main]++] = &pingpong_p2_self[0]->_lf__reaction_0;
        // Initializing action Pingpong.p2.a
        pingpong_p2_self[0]->_lf__a.offset = 0;
        pingpong_p2_self[0]->_lf__a.period = -1;
        pingpong_p2_self[0]->_lf__a.last_tag = NEVER_TAG;
        pingpong_p2_self[0]->_lf__a.mode = NULL;
        _lf_initialize_template((token_template_t*)
                &(pingpong_p2_self[0]->_lf__a),
        0);
        _lf_initialize_template((token_template_t*)
                &(pingpong_p2_self[0]->_lf_a),
        0);
        pingpong_p2_self[0]->_lf__a.status = absent;
        pingpong_p2_self[0]->_lf__reaction_0.deadline = NEVER;
        pingpong_p2_self[0]->_lf__reaction_1.deadline = NEVER;
        pingpong_p2_self[0]->_lf__reaction_2.deadline = NEVER;
        #if !defined LF_SINGLE_THREADED
        pingpong_p2_self[0]->base.reactor_mutex = NULL;
        #endif
        //***** End initializing Pingpong.p2
    }
    {
        _pingpong_main_main_self_t *self = pingpong_main_self[0];
        // ***** Start initializing Pingpong.delay of class _lf_GenDelay_0
        pingpong_delay_self[0] = new___lf_gendelay_0();
        pingpong_delay_self[0]->base.environment = &environments[pingpong_main];
        pingpong_delay_self[0]->_lf_name = "pingpong_delay_lf";
        if (set_python_field_to_c_pointer("__main__",
            pingpong_delay_self[0]->_lf_name,
            0,
            "lf_self",
            pingpong_delay_self[0])) {
          lf_print_error_and_exit("Could not set lf_self pointer delay");
        }
        
        
        // width of -2 indicates that it is not a multiport.
        pingpong_delay_self[0]->_lf_out_width = -2;
        // width of -2 indicates that it is not a multiport.
        pingpong_delay_self[0]->_lf_inp_width = -2;
        // Initializing action Pingpong.delay.act
        pingpong_delay_self[0]->_lf__act.offset = 0;
        pingpong_delay_self[0]->_lf__act.period = -1;
        pingpong_delay_self[0]->_lf__act.last_tag = NEVER_TAG;
        pingpong_delay_self[0]->_lf__act.mode = NULL;
        _lf_initialize_template((token_template_t*)
                &(pingpong_delay_self[0]->_lf__act),
        0);
        _lf_initialize_template((token_template_t*)
                &(pingpong_delay_self[0]->_lf_act),
        0);
        pingpong_delay_self[0]->_lf__act.status = absent;
        pingpong_delay_self[0]->_lf__reaction_0.deadline = NEVER;
        pingpong_delay_self[0]->_lf__reaction_1.deadline = NEVER;
        #if !defined LF_SINGLE_THREADED
        pingpong_delay_self[0]->base.reactor_mutex = NULL;
        #endif
        //***** End initializing Pingpong.delay
    }
    //***** End initializing Pingpong
    // **** Start deferred initialize for Pingpong
    {
        pingpong_main_self[0]->base.name = "Pingpong";
        pingpong_main_self[0]->base.parent = (self_base_t*)NULL;
    
    
    
        // **** Start deferred initialize for Pingpong.p1
        {
            pingpong_p1_self[0]->base.name = "p1";
            pingpong_p1_self[0]->base.parent = (self_base_t*)pingpong_main_self[0];
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of Pingpong.p1.
            pingpong_p1_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 0 of Pingpong.p1
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_2 of Pingpong.p1.
            pingpong_p1_self[0]->_lf__reaction_1.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 1 of Pingpong.p1
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_3 of Pingpong.p1.
            pingpong_p1_self[0]->_lf__reaction_2.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            pingpong_p1_self[0]->_lf__reaction_2.triggers = (trigger_t***)lf_allocate(
                    1, sizeof(trigger_t**),
                    &pingpong_p1_self[0]->base.allocations);
            pingpong_p1_self[0]->_lf__reaction_2.triggered_sizes = (int*)lf_allocate(
                    1, sizeof(int),
                    &pingpong_p1_self[0]->base.allocations);
            pingpong_p1_self[0]->_lf__reaction_2.output_produced = (bool**)lf_allocate(
                    1, sizeof(bool*),
                    &pingpong_p1_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    pingpong_p1_self[0]->_lf__reaction_2.output_produced[count++] = &pingpong_p1_self[0]->_lf_ballOut.is_present;
                }
            }
            
            // ** End initialization for reaction 2 of Pingpong.p1
        
        }
        // **** End of deferred initialize for Pingpong.p1
        // **** Start deferred initialize for Pingpong.p2
        {
            pingpong_p2_self[0]->base.name = "p2";
            pingpong_p2_self[0]->base.parent = (self_base_t*)pingpong_main_self[0];
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of Pingpong.p2.
            pingpong_p2_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 0 of Pingpong.p2
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_2 of Pingpong.p2.
            pingpong_p2_self[0]->_lf__reaction_1.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 1 of Pingpong.p2
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_3 of Pingpong.p2.
            pingpong_p2_self[0]->_lf__reaction_2.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            pingpong_p2_self[0]->_lf__reaction_2.triggers = (trigger_t***)lf_allocate(
                    1, sizeof(trigger_t**),
                    &pingpong_p2_self[0]->base.allocations);
            pingpong_p2_self[0]->_lf__reaction_2.triggered_sizes = (int*)lf_allocate(
                    1, sizeof(int),
                    &pingpong_p2_self[0]->base.allocations);
            pingpong_p2_self[0]->_lf__reaction_2.output_produced = (bool**)lf_allocate(
                    1, sizeof(bool*),
                    &pingpong_p2_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    pingpong_p2_self[0]->_lf__reaction_2.output_produced[count++] = &pingpong_p2_self[0]->_lf_ballOut.is_present;
                }
            }
            
            // ** End initialization for reaction 2 of Pingpong.p2
        
        }
        // **** End of deferred initialize for Pingpong.p2
        // **** Start deferred initialize for Pingpong.delay
        {
            pingpong_delay_self[0]->base.name = "delay";
            pingpong_delay_self[0]->base.parent = (self_base_t*)pingpong_main_self[0];
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of Pingpong.delay.
            pingpong_delay_self[0]->_lf__reaction_0.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            pingpong_delay_self[0]->_lf__reaction_0.triggers = (trigger_t***)lf_allocate(
                    1, sizeof(trigger_t**),
                    &pingpong_delay_self[0]->base.allocations);
            pingpong_delay_self[0]->_lf__reaction_0.triggered_sizes = (int*)lf_allocate(
                    1, sizeof(int),
                    &pingpong_delay_self[0]->base.allocations);
            pingpong_delay_self[0]->_lf__reaction_0.output_produced = (bool**)lf_allocate(
                    1, sizeof(bool*),
                    &pingpong_delay_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    pingpong_delay_self[0]->_lf__reaction_0.output_produced[count++] = &pingpong_delay_self[0]->_lf_out.is_present;
                }
            }
            
            // ** End initialization for reaction 0 of Pingpong.delay
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_2 of Pingpong.delay.
            pingpong_delay_self[0]->_lf__reaction_1.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 1 of Pingpong.delay
        
        }
        // **** End of deferred initialize for Pingpong.delay
    }
    // **** End of deferred initialize for Pingpong
    // **** Start non-nested deferred initialize for Pingpong
    {
    
    
    
        // **** Start non-nested deferred initialize for Pingpong.p1
        {
        
            // For reference counting, set num_destinations for port Pingpong.p1.ballOut.
            // Iterate over range Pingpong.p1.ballOut(0,1)->[Pingpong.delay.inp(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                pingpong_p1_self[src_runtime]->_lf_ballOut._base.num_destinations = 1;
                pingpong_p1_self[src_runtime]->_lf_ballOut._base.source_reactor = (self_base_t*)pingpong_p1_self[src_runtime];
            }
            {
                int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
                // Iterate over range Pingpong.p1.ballOut(0,1)->[Pingpong.delay.inp(0,1)].
                {
                    int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                    int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                    int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Reaction 2 of Pingpong.p1 triggers 1 downstream reactions
                    // through port Pingpong.p1.ballOut.
                    pingpong_p1_self[src_runtime]->_lf__reaction_2.triggered_sizes[triggers_index[src_runtime]] = 1;
                    // For reaction 2 of Pingpong.p1, allocate an
                    // array of trigger pointers for downstream reactions through port Pingpong.p1.ballOut
                    trigger_t** trigger_array = (trigger_t**)lf_allocate(
                            1, sizeof(trigger_t*),
                            &pingpong_p1_self[src_runtime]->base.allocations); 
                    pingpong_p1_self[src_runtime]->_lf__reaction_2.triggers[triggers_index[src_runtime]++] = trigger_array;
                }
                for (int i = 0; i < 1; i++) triggers_index[i] = 0;
                // Iterate over ranges Pingpong.p1.ballOut(0,1)->[Pingpong.delay.inp(0,1)] and Pingpong.delay.inp(0,1).
                {
                    int src_runtime = 0; // Runtime index.
                    SUPPRESS_UNUSED_WARNING(src_runtime);
                    int src_channel = 0; // Channel index.
                    SUPPRESS_UNUSED_WARNING(src_channel);
                    int src_bank = 0; // Bank index.
                    SUPPRESS_UNUSED_WARNING(src_bank);
                    // Iterate over range Pingpong.delay.inp(0,1).
                    {
                        int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                        int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                        int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                        // Point to destination port Pingpong.delay.inp's trigger struct.
                        pingpong_p1_self[src_runtime]->_lf__reaction_2.triggers[triggers_index[src_runtime] + src_channel][0] = &pingpong_delay_self[dst_runtime]->_lf__inp;
                    }
                }
            }
        
        }
        // **** End of non-nested deferred initialize for Pingpong.p1
        // **** Start non-nested deferred initialize for Pingpong.p2
        {
        
            // For reference counting, set num_destinations for port Pingpong.p2.ballOut.
            // Iterate over range Pingpong.p2.ballOut(0,1)->[Pingpong.p1.ballIn(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                pingpong_p2_self[src_runtime]->_lf_ballOut._base.num_destinations = 1;
                pingpong_p2_self[src_runtime]->_lf_ballOut._base.source_reactor = (self_base_t*)pingpong_p2_self[src_runtime];
            }
            {
                int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
                // Iterate over range Pingpong.p2.ballOut(0,1)->[Pingpong.p1.ballIn(0,1)].
                {
                    int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                    int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                    int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Reaction 2 of Pingpong.p2 triggers 1 downstream reactions
                    // through port Pingpong.p2.ballOut.
                    pingpong_p2_self[src_runtime]->_lf__reaction_2.triggered_sizes[triggers_index[src_runtime]] = 1;
                    // For reaction 2 of Pingpong.p2, allocate an
                    // array of trigger pointers for downstream reactions through port Pingpong.p2.ballOut
                    trigger_t** trigger_array = (trigger_t**)lf_allocate(
                            1, sizeof(trigger_t*),
                            &pingpong_p2_self[src_runtime]->base.allocations); 
                    pingpong_p2_self[src_runtime]->_lf__reaction_2.triggers[triggers_index[src_runtime]++] = trigger_array;
                }
                for (int i = 0; i < 1; i++) triggers_index[i] = 0;
                // Iterate over ranges Pingpong.p2.ballOut(0,1)->[Pingpong.p1.ballIn(0,1)] and Pingpong.p1.ballIn(0,1).
                {
                    int src_runtime = 0; // Runtime index.
                    SUPPRESS_UNUSED_WARNING(src_runtime);
                    int src_channel = 0; // Channel index.
                    SUPPRESS_UNUSED_WARNING(src_channel);
                    int src_bank = 0; // Bank index.
                    SUPPRESS_UNUSED_WARNING(src_bank);
                    // Iterate over range Pingpong.p1.ballIn(0,1).
                    {
                        int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                        int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                        int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                        // Point to destination port Pingpong.p1.ballIn's trigger struct.
                        pingpong_p2_self[src_runtime]->_lf__reaction_2.triggers[triggers_index[src_runtime] + src_channel][0] = &pingpong_p1_self[dst_runtime]->_lf__ballIn;
                    }
                }
            }
        
        }
        // **** End of non-nested deferred initialize for Pingpong.p2
        // **** Start non-nested deferred initialize for Pingpong.delay
        {
        
            // For reference counting, set num_destinations for port Pingpong.delay.out.
            // Iterate over range Pingpong.delay.out(0,1)->[Pingpong.p2.ballIn(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                pingpong_delay_self[src_runtime]->_lf_out._base.num_destinations = 1;
                pingpong_delay_self[src_runtime]->_lf_out._base.source_reactor = (self_base_t*)pingpong_delay_self[src_runtime];
            }
            {
                int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
                // Iterate over range Pingpong.delay.out(0,1)->[Pingpong.p2.ballIn(0,1)].
                {
                    int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                    int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                    int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Reaction 0 of Pingpong.delay triggers 1 downstream reactions
                    // through port Pingpong.delay.out.
                    pingpong_delay_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
                    // For reaction 0 of Pingpong.delay, allocate an
                    // array of trigger pointers for downstream reactions through port Pingpong.delay.out
                    trigger_t** trigger_array = (trigger_t**)lf_allocate(
                            1, sizeof(trigger_t*),
                            &pingpong_delay_self[src_runtime]->base.allocations); 
                    pingpong_delay_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
                }
                for (int i = 0; i < 1; i++) triggers_index[i] = 0;
                // Iterate over ranges Pingpong.delay.out(0,1)->[Pingpong.p2.ballIn(0,1)] and Pingpong.p2.ballIn(0,1).
                {
                    int src_runtime = 0; // Runtime index.
                    SUPPRESS_UNUSED_WARNING(src_runtime);
                    int src_channel = 0; // Channel index.
                    SUPPRESS_UNUSED_WARNING(src_channel);
                    int src_bank = 0; // Bank index.
                    SUPPRESS_UNUSED_WARNING(src_bank);
                    // Iterate over range Pingpong.p2.ballIn(0,1).
                    {
                        int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                        int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                        int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                        // Point to destination port Pingpong.p2.ballIn's trigger struct.
                        pingpong_delay_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &pingpong_p2_self[dst_runtime]->_lf__ballIn;
                    }
                }
            }
        
        }
        // **** End of non-nested deferred initialize for Pingpong.delay
    }
    // **** End of non-nested deferred initialize for Pingpong
    // Connect inputs and outputs for reactor Pingpong.
    // Connect inputs and outputs for reactor Pingpong.p1.
    // Connect Pingpong.p1.ballOut(0,1)->[Pingpong.delay.inp(0,1)] to port Pingpong.delay.inp(0,1)
    // Iterate over ranges Pingpong.p1.ballOut(0,1)->[Pingpong.delay.inp(0,1)] and Pingpong.delay.inp(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range Pingpong.delay.inp(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            pingpong_delay_self[dst_runtime]->_lf_inp = (__lf_gendelay_0_inp_t*)&pingpong_p1_self[src_runtime]->_lf_ballOut;
        }
    }
    // Connect inputs and outputs for reactor Pingpong.p2.
    // Connect Pingpong.p2.ballOut(0,1)->[Pingpong.p1.ballIn(0,1)] to port Pingpong.p1.ballIn(0,1)
    // Iterate over ranges Pingpong.p2.ballOut(0,1)->[Pingpong.p1.ballIn(0,1)] and Pingpong.p1.ballIn(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range Pingpong.p1.ballIn(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            pingpong_p1_self[dst_runtime]->_lf_ballIn = (_player_ballIn_t*)&pingpong_p2_self[src_runtime]->_lf_ballOut;
        }
    }
    // Connect inputs and outputs for reactor Pingpong.delay.
    // Connect Pingpong.delay.out(0,1)->[Pingpong.p2.ballIn(0,1)] to port Pingpong.p2.ballIn(0,1)
    // Iterate over ranges Pingpong.delay.out(0,1)->[Pingpong.p2.ballIn(0,1)] and Pingpong.p2.ballIn(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range Pingpong.p2.ballIn(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            pingpong_p2_self[dst_runtime]->_lf_ballIn = (_player_ballIn_t*)&pingpong_delay_self[src_runtime]->_lf_out;
        }
    }
    {
        // Add action Pingpong.p1.a to array of is_present fields.
        environments[pingpong_main].is_present_fields[0 + (0) * 1]
                = (bool *) &pingpong_p1_self[0]->_lf__a.status;
        #ifdef FEDERATED_DECENTRALIZED
        // Add action Pingpong.p1.a to array of intended_tag fields.
        environments[pingpong_main]._lf_intended_tag_fields[0 + (0) * 1]
                = &pingpong_p1_self[0]->_lf_a.intended_tag;
        #endif // FEDERATED_DECENTRALIZED
    }
    {
        // Add action Pingpong.p2.a to array of is_present fields.
        environments[pingpong_main].is_present_fields[1 + (0) * 1]
                = (bool *) &pingpong_p2_self[0]->_lf__a.status;
        #ifdef FEDERATED_DECENTRALIZED
        // Add action Pingpong.p2.a to array of intended_tag fields.
        environments[pingpong_main]._lf_intended_tag_fields[1 + (0) * 1]
                = &pingpong_p2_self[0]->_lf_a.intended_tag;
        #endif // FEDERATED_DECENTRALIZED
    }
    {
        // Add action Pingpong.delay.act to array of is_present fields.
        environments[pingpong_main].is_present_fields[2 + (0) * 1]
                = (bool *) &pingpong_delay_self[0]->_lf__act.status;
        #ifdef FEDERATED_DECENTRALIZED
        // Add action Pingpong.delay.act to array of intended_tag fields.
        environments[pingpong_main]._lf_intended_tag_fields[2 + (0) * 1]
                = &pingpong_delay_self[0]->_lf_act.intended_tag;
        #endif // FEDERATED_DECENTRALIZED
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            // Add output port Pingpong.p1.ballOut to array of is_present fields.
            environments[pingpong_main].is_present_fields[(0) * 1 + 3 + count] = &pingpong_p1_self[0]->_lf_ballOut.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add output port Pingpong.p1.ballOut to array of intended_tag fields.
            environments[pingpong_main]._lf_intended_tag_fields[(0) * 1 + 3 + count] = &pingpong_p1_self[0]->_lf_ballOut.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
        }
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            // Add output port Pingpong.p2.ballOut to array of is_present fields.
            environments[pingpong_main].is_present_fields[(0) * 1 + 4 + count] = &pingpong_p2_self[0]->_lf_ballOut.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add output port Pingpong.p2.ballOut to array of intended_tag fields.
            environments[pingpong_main]._lf_intended_tag_fields[(0) * 1 + 4 + count] = &pingpong_p2_self[0]->_lf_ballOut.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
        }
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            // Add output port Pingpong.delay.out to array of is_present fields.
            environments[pingpong_main].is_present_fields[(0) * 1 + 5 + count] = &pingpong_delay_self[0]->_lf_out.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add output port Pingpong.delay.out to array of intended_tag fields.
            environments[pingpong_main]._lf_intended_tag_fields[(0) * 1 + 5 + count] = &pingpong_delay_self[0]->_lf_out.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
        }
    }
    
    // Set reaction priorities for ReactorInstance Pingpong
    {
    
        // Set reaction priorities for ReactorInstance Pingpong.p1
        {
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            pingpong_p1_self[0]->_lf__reaction_0.index = lf_combine_deadline_and_level(9223372036854775807, 0);
            // index is the OR of level 3 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            pingpong_p1_self[0]->_lf__reaction_1.index = lf_combine_deadline_and_level(9223372036854775807, 3);
            // index is the OR of level 4 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            pingpong_p1_self[0]->_lf__reaction_2.index = lf_combine_deadline_and_level(9223372036854775807, 4);
        }
    
    
        // Set reaction priorities for ReactorInstance Pingpong.p2
        {
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            pingpong_p2_self[0]->_lf__reaction_0.index = lf_combine_deadline_and_level(9223372036854775807, 0);
            // index is the OR of level 1 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            pingpong_p2_self[0]->_lf__reaction_1.index = lf_combine_deadline_and_level(9223372036854775807, 1);
            // index is the OR of level 2 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            pingpong_p2_self[0]->_lf__reaction_2.index = lf_combine_deadline_and_level(9223372036854775807, 2);
        }
    
    
        // Set reaction priorities for ReactorInstance Pingpong.delay
        {
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            pingpong_delay_self[0]->_lf__reaction_0.index = lf_combine_deadline_and_level(9223372036854775807, 0);
            // index is the OR of level 5 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            pingpong_delay_self[0]->_lf__reaction_1.index = lf_combine_deadline_and_level(9223372036854775807, 5);
        }
    
    }
    
    // Initialize the scheduler for enclave `pingpong_main` in a private scope
    {
        size_t num_reactions_per_level[6] = {3, 1, 1, 1, 1, 1};
        sched_params_t sched_params = (sched_params_t) {
            .num_reactions_per_level = &num_reactions_per_level[0],
            .num_reactions_per_level_size = (size_t) 6
        };
        lf_sched_init(
            &environments[pingpong_main],
            environments[pingpong_main].num_workers,
            &sched_params
        );
    }
    #ifdef EXECUTABLE_PREAMBLE
    _lf_executable_preamble(&environments[0]);
    #endif
    #ifdef FEDERATED
    initialize_triggers_for_federate();
    #endif // FEDERATED
}
void logical_tag_complete(tag_t tag_to_send) {
 #ifdef FEDERATED_CENTRALIZED
     lf_latest_tag_confirmed(tag_to_send);
 #else
     (void) tag_to_send;
 #endif // FEDERATED_CENTRALIZED

}
#ifndef FEDERATED
void lf_terminate_execution(environment_t* env) {
    (void) env;
}
#endif
