#include "pythontarget.h"
#include <limits.h>
#include "low_level_platform/api/low_level_platform.h"
#include "include/api/schedule.h"
#include "include/core/reactor.h"
#include "include/core/reactor_common.h"
#include "include/core/threaded/scheduler.h"
#include "include/core/mixed_radix.h"
#include "include/core/port.h"
#include "include/core/environment.h"
int lf_reactor_c_main(int argc, const char* argv[]);
// Code generated by the Lingua Franca compiler from:
// file://Users/russl8/github/lf-py/intro/src/Helloworld.lf
#define LOG_LEVEL 2

int main(int argc, const char* argv[]) {
    return lf_reactor_c_main(argc, argv);
}
void lf_set_default_command_line_options() {}
#include "_helloworld_main.h"
typedef enum {
    helloworld_main,
    num_environments
} _enclave_id;
// The global array of environments associated with each enclave
static environment_t environments[num_environments];
// 'Create' and initialize the environments in the program
void lf_create_environments() {
    environment_init(&environments[helloworld_main],"helloworld_main",helloworld_main,_lf_number_of_workers,0,1,0,0,0,0,0,0,NULL);
}
// Update the pointer argument to point to the beginning of the environment array
// and return the size of that array
int _lf_get_environments(environment_t ** return_envs) {
   (*return_envs) = (environment_t *) environments;
   return num_environments;
}
// Arrays representing the enclaves downstream of `helloworld_main_downstream`
#define HELLOWORLD_MAIN_NUM_DOWNSTREAM 0
// No downstreams, but 0-length arrays not allowed by MSVC (C2466)
int helloworld_main_downstream[1] = {-1};
// Arrays representing the enclaves upstream of `helloworld_main_upstream`
#define HELLOWORLD_MAIN_NUM_UPSTREAM 0
// No upstreams, but 0-length arrays not allowed by MSVC (C2466)
int helloworld_main_upstream[1] = {-1};
// No upstreams, but 0-length arrays not allowed by MSVC (C2466)
interval_t helloworld_main_upstream_delay[1] = {FOREVER};
// Writes a pointer to the array of upstream enclaves into `result` and returns the length
int lf_get_upstream_of(int enclave_id, int ** result) {
    int num_upstream;
    int* upstream;
    switch(enclave_id) { 
        case helloworld_main:
            num_upstream = HELLOWORLD_MAIN_NUM_UPSTREAM;
            upstream = &helloworld_main_upstream[0];
            break;
        default:
            lf_print_error_and_exit("Illegal enclave_id %u", enclave_id);
            break;
        }
    (*result) = upstream;
    return num_upstream;
}
// Writes a pointer to the array of downstream enclaves into `result` and returns the length
int lf_get_downstream_of(int enclave_id, int ** result) {
    int num_downstream;
    int* downstream;
    switch(enclave_id) { 
        case helloworld_main:
            num_downstream = HELLOWORLD_MAIN_NUM_DOWNSTREAM;
            downstream = &helloworld_main_downstream[0];
            break;
        default:
            lf_print_error_and_exit("Illegal enclave_id %u", enclave_id);
            break;
        }
    (*result) = downstream;
    return num_downstream;
}
// Writes a pointer to the array of upstream delays into `result` and returns the length
int lf_get_upstream_delay_of(int enclave_id, interval_t ** result) {
    int num_upstream;
    interval_t* delay;
    switch(enclave_id) { 
        case helloworld_main:
            num_upstream = HELLOWORLD_MAIN_NUM_UPSTREAM;
            delay = &helloworld_main_upstream_delay[0];
            break;
        default:
            lf_print_error_and_exit("Illegal enclave_id %u", enclave_id);
            break;
        }
    (*result) = delay;
    return num_upstream;
}
void _lf_initialize_trigger_objects() {
    int startup_reaction_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(startup_reaction_count);
    int shutdown_reaction_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(shutdown_reaction_count);
    int reset_reaction_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(reset_reaction_count);
    int timer_triggers_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(timer_triggers_count);
    int modal_state_reset_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(modal_state_reset_count);
    int modal_reactor_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(modal_reactor_count);
    int watchdog_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(watchdog_count);
    int bank_index;
    SUPPRESS_UNUSED_WARNING(bank_index);
    int watchdog_number = 0;
    SUPPRESS_UNUSED_WARNING(watchdog_number);
    _helloworld_main_main_self_t* helloworld_main_self[1];
    SUPPRESS_UNUSED_WARNING(helloworld_main_self);
    // ***** Start initializing Helloworld of class Helloworld
    helloworld_main_self[0] = new__helloworld_main();
    helloworld_main_self[0]->base.environment = &environments[helloworld_main];
    helloworld_main_self[0]->_lf_name = "helloworld_main_lf";
    helloworld_main_self[0]->_lf_py_reaction_function_0 = 
    get_python_function("__main__", 
        helloworld_main_self[0]->_lf_name,
        0,
        "reaction_function_0");
    if(helloworld_main_self[0]->_lf_py_reaction_function_0 == NULL) {
        lf_print_error_and_exit("Could not load function reaction_function_0");
    }
    if (set_python_field_to_c_pointer("__main__",
        helloworld_main_self[0]->_lf_name,
        0,
        "lf_self",
        helloworld_main_self[0])) {
      lf_print_error_and_exit("Could not set lf_self pointer Helloworld");
    }
    environments[helloworld_main].startup_reactions[startup_reaction_count[helloworld_main]++] = &helloworld_main_self[0]->_lf__reaction_0;
    
    helloworld_main_self[0]->_lf__reaction_0.deadline = NEVER;
    #if !defined LF_SINGLE_THREADED
    helloworld_main_self[0]->base.reactor_mutex = NULL;
    #endif
    //***** End initializing Helloworld
    // **** Start deferred initialize for Helloworld
    {
        helloworld_main_self[0]->base.name = "Helloworld";
        helloworld_main_self[0]->base.parent = (self_base_t*)NULL;
    
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_1 of Helloworld.
        helloworld_main_self[0]->_lf__reaction_0.num_outputs = 0;
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
        }
        
        // ** End initialization for reaction 0 of Helloworld
    
    }
    // **** End of deferred initialize for Helloworld
    // **** Start non-nested deferred initialize for Helloworld
    {
    
    
    
    }
    // **** End of non-nested deferred initialize for Helloworld
    // Connect inputs and outputs for reactor Helloworld.

    
    // Set reaction priorities for ReactorInstance Helloworld
    {
        // index is the OR of level 0 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        helloworld_main_self[0]->_lf__reaction_0.index = lf_combine_deadline_and_level(9223372036854775807, 0);
    }
    
    // Initialize the scheduler for enclave `helloworld_main` in a private scope
    {
        size_t num_reactions_per_level[1] = {1};
        sched_params_t sched_params = (sched_params_t) {
            .num_reactions_per_level = &num_reactions_per_level[0],
            .num_reactions_per_level_size = (size_t) 1
        };
        lf_sched_init(
            &environments[helloworld_main],
            environments[helloworld_main].num_workers,
            &sched_params
        );
    }
    #ifdef EXECUTABLE_PREAMBLE
    _lf_executable_preamble(&environments[0]);
    #endif
    #ifdef FEDERATED
    initialize_triggers_for_federate();
    #endif // FEDERATED
}
void logical_tag_complete(tag_t tag_to_send) {
 #ifdef FEDERATED_CENTRALIZED
     lf_latest_tag_confirmed(tag_to_send);
 #else
     (void) tag_to_send;
 #endif // FEDERATED_CENTRALIZED

}
#ifndef FEDERATED
void lf_terminate_execution(environment_t* env) {
    (void) env;
}
#endif
